apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    chart_version: {{ .Chart.Version | quote }}
    helm_revision: {{ .Release.Revision | quote }}
    helm_release: {{ .Release.Name | quote }}
{{ toYaml .Values.labels | indent 4 }}
spec:
  type: LoadBalancer
  selector:
{{ toYaml .Values.labels | indent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
