version: 2.1

references:
  ci_image: &ci_image
    image: circleci/node:latest
  terraform_image: &terraform_image
    image: hashicorp/terraform:0.12.20

jobs:
  docker-build-push-to-dockerhub:
    docker:
      - *ci_image
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "${DOCKERHUB_TOKEN}" | docker login --username="irynalian" --password-stdin
      - run: docker build -t irynalian/serverless:latest .
      - run: docker push irynalian/serverless:latest
  terraform:
    parameters:
      ci_env:
        description: The AWS environment that will be accessed
        type: enum
        enum: ["serverless", "staging", "production"]
      terraform_action:
        description: Action for terraform to perform
        type: enum
        enum: ["plan", "apply"]
    docker:
      - *terraform_image
    steps:
      - checkout
      - run:
          name: Terraform << parameters.terraform_action >> Infrastructure Changes
          command: |
            cat > ~/.terraformrc \<<EOF
            credentials "app.terraform.io" {
              token = "${TF_TOKEN}"
            }
            EOF
            export TF_WORKSPACE=<< parameters.ci_env >>
            cd terraform
            terraform init
            terraform output
            if [ << parameters.terraform_action >> = "apply" ]
            then
                terraform << parameters.terraform_action >> -auto-approve
            else
                terraform << parameters.terraform_action >>
            fi
  deploy:
    docker:
      - *ci_image
    steps:
      - checkout
      - run:
          name: Helm Lint
          command: helm lint --strict -f deploy/${CI_ENV}/${CIRCLE_PROJECT_REPONAME}.values.yml deploy/charts/${CIRCLE_PROJECT_REPONAME}
      - run:
          name: Helm Template and Kubeval
          command: helm template -f deploy/${CI_ENV}/${CIRCLE_PROJECT_REPONAME}.values.yml deploy/charts/${CIRCLE_PROJECT_REPONAME} | kubeval
      - run:
          name: Prepare kubectl
          command: prepare-kubectl
      - run:
          name: Helm Deploy
          command: ROK8S_HELM_DEPLOY_EXTRAARGS="--force --atomic --description ${CI_SHA1} --set schema_rambler_password=${SCHEMA_RAMBLER_PASSWORD} --set secretSum=$(sha256sum deploy/${CI_ENV}/${CIRCLE_PROJECT_REPONAME}-env.secret.sops.yml | awk '{ print $1 }')"
            helm-deploy -f deploy/${CI_ENV}/config.env

workflows:
  build:
    jobs:
      - docker-build-push-to-dockerhub
      - terraform:
          name: staging-terraform-plan
          context: stockx-services
          ci_env: staging
          terraform_action: plan
          requires:
            - docker-build-push-to-dockerhub
      - staging-terraform-approval:
          type: approval
          requires:
            - staging-terraform-plan
      - terraform:
          name: staging-terraform-apply
          context: stockx-services
          ci_env: staging
          terraform_action: apply
          requires:
            - staging-terraform-approval
      - deploy:
          requires:
            - staging-terraform-apply
