apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-env"
  labels:
    chart_version: {{ .Chart.Version | quote }}
    helm_revision: {{ .Release.Revision | quote }}
    helm_release: {{ .Release.Name | quote }}
{{ toYaml .Values.labels | indent 4 }}
data:
{{ toYaml .Values.envConfig | indent 2 }}
